### ISSUE TITLE
GLM does not seem to have files data source options for (datafile, labelfile)

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#101]
Hello,

I am trying to run the GLM model with a files data source. However, there does not seem to be an option for specifying a files data source with _two_ file patterns. As an example, the Random Forest class has this line:

```
def learner(datafile:String, labelfile:String):(Learner, FsOpts) = learner(List(FileSource.simpleEnum(datafile, 0, 1), FileSource.simpleEnum(labelfile, 0, 1)))
```

which will combine the data file and label file string patterns and then allow a learner to run. This way, I can call:

```
val (nn1,opts1) = RandomForest.learner("data_%02d.fmat.lz4", "label_%02d.fmat.lz4");
```

But there does not seem to be a comparable option; this is not allowed:

```
val (nn1,opts1) = GLM.learner("data_%02d.fmat.lz4", "label_%02d.fmat.lz4");
```

And this is verified by a look at the GLM.scala source code. Would it be possible for GLM to have this option? In addition, GLM would also need to have "0" through "3" to indicate the four different GLM learners that are currently implemented.

Thanks,
Daniel

**Comment by jcanny** [comment]
Since GLM has other options beyond data and labels for the datasource, it takes a list of file name patterns. So

val (nn,opts) = GLM.learner(List("data_%02d.fmat.lz4", "label_%02d.fmat.lz4"))

should do what you want.

**Comment by jcanny** [comment]
PS, BIDMach has a modular architecture and its very easy to put together a Learner using whatever combination of source, model, updater etc, that you want. You can use those convenience functions (e.g. GLM.learner) as a template for your own designs.

**Comment by DanielTakeshi** [comment]
For the benefit of anyone else who's reading this: John's suggestion works.
