### ISSUE TITLE
Question about community of BIDMach and BIDMat

### ISSUE THREAD

**Issue by hsaputra** [BIDData/BIDMach#102]
Hi All,

I love the idea of the project, and it is inline with what I was trying to build, so I am thinking about trying it out and maybe integrate it to my project.

So, been trying to get info about the community and how to contribute, but could not find anything from the project site:
http://bid2.berkeley.edu/bid-data-project/

Is there any dev or user mailing list to start collaborate or maybe Google groups? 
I could not find such information about it, that is why I opened this issue (seemed like the only way to communicate about the project).

Thanks for your time,

Henry

**Comment by jcanny** [comment]
Yes, there is a Google group here:
https://groups.google.com/forum/#!forum/bidmach-users-group

I just linked it from the github and project wiki landing pages. 

re: dev and user groups, what would you suggest?

**Comment by hsaputra** [comment]
Thanks for the response and link to  the Google group, @jcanny.

We can use the Google user group as the main communication for end users, but maybe create another one called bidmach-dev-group to have more discussions about developing features or extending the BIDMach and BIDMat projects.

Also, the website (http://bid2.berkeley.edu/bid-data-project) does not seem to allow external users to comment. Maybe if possible to add moderated user comment ability would help to get more adoption and popularity of the project.

I like how some other projects also using https://gitter.im/ or to support chat to enable more collaborate environment.

Hope these comments help.

**Comment by mattmacy** [comment]
With regards to our community discussion earlier today -
@jcanny is your @cs.berkeley.edu address not the way to contact you directly?

**Comment by DanielTakeshi** [comment]
@mattmacy yes, that is his email (whatever's listed on his website). However, you also have to remember that like many faculty, he gets hundreds of emails every day and can't respond to every one of them quickly. The community of *developers* for BIDMach/BIDMat is relatively small and confined to our group and a few others (or one could argue John does almost everything, which is true).
