### ISSUE TITLE
sbt package fails on latest

### ISSUE THREAD

**Issue by mattmacy** [BIDData/BIDMach#108]
[info] downloading http://repo1.maven.org/maven2/jline/jline/2.12/jline-2.12.jar ...
[info] 	[SUCCESSFUL ] jline#jline;2.12!jline.jar (133ms)
[info] Done updating.
[info] Compiling 87 Scala sources and 9 Java sources to /home/mmacy/devel/BIDMach/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.2. Compiling...
[info]   Compilation completed in 5.43 s
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:3: object TMat is not a member of package BIDMat
[error] import BIDMat.{Mat,SBMat,CMat,CSMat,DMat,FMat,FND,GMat,GDMat,GIMat,GSMat,GSDMat,GND,HMat,IMat,JSON,LMat,ND,SMat,SDMat,TMat}
[error]        ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:357: not found: type TMat
[error]       case tt:TMat => new TMat(tt.nrows, tt.ncols, tt.y, tt.x, tt.tiles.map(convertMat(_, useGPU, useDouble).asInstanceOf[Mat]));
[error]               ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:357: not found: type TMat
[error]       case tt:TMat => new TMat(tt.nrows, tt.ncols, tt.y, tt.x, tt.tiles.map(convertMat(_, useGPU, useDouble).asInstanceOf[Mat]));
[error]                           ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:357: value y is not a member of BIDMat.ND
[error]       case tt:TMat => new TMat(tt.nrows, tt.ncols, tt.y, tt.x, tt.tiles.map(convertMat(_, useGPU, useDouble).asInstanceOf[Mat]));
[error]                                                       ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:357: value x is not a member of BIDMat.ND
[error]       case tt:TMat => new TMat(tt.nrows, tt.ncols, tt.y, tt.x, tt.tiles.map(convertMat(_, useGPU, useDouble).asInstanceOf[Mat]));
[error]                                                             ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/models/Model.scala:357: value tiles is not a member of BIDMat.ND
[error]       case tt:TMat => new TMat(tt.nrows, tt.ncols, tt.y, tt.x, tt.tiles.map(convertMat(_, useGPU, useDouble).asInstanceOf[Mat]));
[error]                                                                   ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/networks/Net.scala:3: object TMat is not a member of package BIDMat
[error] import BIDMat.{Mat,SBMat,CMat,DMat,FMat,IMat,LMat,HMat,GMat,GDMat,GIMat,GLMat,GSMat,GSDMat,JSON,SMat,SDMat,TMat}
[error]        ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/networks/layers/LinLayer.scala:3: object TMat is not a member of package BIDMat
[error] import BIDMat.{Mat,SBMat,CMat,DMat,FMat,IMat,LMat,HMat,GMat,GDMat,GIMat,GLMat,GSMat,GSDMat,SMat,SDMat,TMat}
[error]        ^
[error] /home/mmacy/devel/BIDMach/src/main/scala/BIDMach/networks/layers/LinLayer.scala:37: not found: value TMat
[error]       val out = TMat(nr, nc, y, x, h, w, zeros(1,1));
[error]                 ^
[error] 9 errors found
[error] (compile:compile) Compilation failed
[error] Total time: 26 s, completed Apr 14, 2016 5:36:43 PM

**Comment by jcanny** [comment]
BIDMach is using a new type TMat from BIDMat. You'll need to get the latest BIDMat library by doing ./getdevlibs.sh in the BIDMach directory before compiling.

**Comment by mattmacy** [comment]
I cloned the BIDMach repo  an hour ago. I then ran getdevlibs.sh 45 minutes ago - just prior to running ./sbt package which was immediately prior to filing this issue. Unless you just updated BIDMat.jar it's unclear to me where the error is on my end. Thanks.

**Comment by mattmacy** [comment]
It looks like you've updated BIDMat.jar. In the meantime. ./sbt package succeeds. Thanks.
