### ISSUE TITLE
nn.predict always returns 0

### ISSUE THREAD

**Issue by kevinkilroy** [BIDData/BIDMach#109]
Hi,
I'm trying to run a simple Linear Regression model but the results of nn.predict are always 0

```
Option Name       Type          Value
===========       ====          =====
addConstFeat      boolean       false
autoReset         boolean       true
batchSize         int           3
dim               int           256
doubleScore       boolean       false
epsilon           float         1.0E-5
evalStep          int           11
featThreshold     Mat           null
featType          int           1
initsumsq         float         1.0E-5
iweight           FMat          null
links             IMat          0
lrate             FMat          1
mask              FMat          null
npasses           int           2
nzPerColumn       int           0
pstep             float         0.01
putBack           int           -1
r1nmats           int           1
reg1weight        FMat          1.0000e-07
resFile           String        null
rmask             FMat          null
sample            float         1.0
sizeMargin        float         3.0
startBlock        int           8000
targets           FMat          null
targmap           FMat          null
texp              FMat          0.50000
useGPU            boolean       true
vexp              FMat          0.50000
waitsteps         int           2
()
corpus perplexity=1.000000
pass= 0
14.00%, ll=-112.88580, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.02
29.00%, ll=-39.68376, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.01
44.00%, ll=-208.15828, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.02
59.00%, ll=-41.27533, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.02
74.00%, ll=-19.18407, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.02
89.00%, ll=-16.87099, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.03
100.00%, ll=-120.24606, gf=0.000, secs=0.0, GB=0.00, MB/s= 0.02
Time=0.0350 secs, gflops=0.00
corpus perplexity=1.000000
Predicting
```

My matrices/code look like this:

```
    var X_train = data(0->trainSize,0)
    X_train = X_train.t // 2x67
    val y_train = data(0->trainSize,1).t // 1 x 67
    var X_test = data(trainSize->data.nr,0)
    X_test = X_test.t // 2 x 30
    val preds = zeros(1, X_test.nc) // 1 x 30
    val (mm:Learner, mopts:LearnOptions) = GLM.learner(X_train, y_train, GLM.linear)
    mm.train


    val (nn:Learner, nopts:LearnOptions) = GLM.predictor(mm.model, X_test, preds, 0)
    nn.predict 
```
Please note, I'm using 0.97 version as my GPU only supports upto CUDA 6.5.

I appreciate the dataset is small, but I'm trying to reproduce the Linear Regression model from an online course that I'm taking (Andrew Ng Machine Learning coursera course). I've tried increasing the number of passes but it makes no difference

Any help would be appreciated.

Thanks,

**Comment by jcanny** [comment]
Its very hard to support older versions, and predict functionality was defninitely poor back then.

You should be able to compile the current code under cuda 6.5. We support 6.5 for Tegra TK1 compatibility.  The main change is to install the jcuda libraries for JCUDA 6.5. in BIDMach/lib, and use the bidmach65 script to start BIDMach. You'll need to recompile the binaries fro your platofrm

cd BIDMach/jni/src
./configure
make installcudalib

then go back to BIDMach/ and do 
./sbt package

**Comment by kevinkilroy** [comment]
Thanks I'll give it a go.

**Comment by kevinkilroy** [comment]
Almost working, this is from latest code cloned from master....
Loading /Users/kevinkilroy/software/biddata/BIDMach/lib/bidmach_init.scala...
import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, GND, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
import BIDMach.Learner
import BIDMach.models.{Click, FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA, RandomForest, SVD}
import BIDMach.networks.Net
import BIDMach.datasources.{DataSource, MatSource, FileSource, SFileSource}
import BIDMach.datasinks.{DataSink, MatSink}
import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, Grad, IncMult, IncNorm, Telescoping}
import BIDMach.causal.IPTW
2 CUDA devices found, CUDA version 6.5

Welcome to Scala version 2.11.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77).
Type in expressions to have them evaluated.
Type :help for more information.


.....

However when training....

﻿﻿scala> mm.train
corpus perplexity=2.069916
java.lang.RuntimeException: CUDA kernel error 8 in CUMAT.applyop
  at BIDMat.GMat.gOp(GMat.scala:849)
  at BIDMat.GMat.unary_$minus(GMat.scala:1267)
  at BIDMat.GMat.unary_$minus(GMat.scala:19)
  at BIDMach.models.GLM.init(GLM.scala:115)
  at BIDMach.Learner.init(Learner.scala:62)
  at BIDMach.Learner.firstPass(Learner.scala:93)
  at BIDMach.Learner.retrain(Learner.scala:81)
  at BIDMach.Learner.train(Learner.scala:70)
  ... 33 elided

**Comment by kevinkilroy** [comment]
I will close this issue as using 1.0.3 I am getting prediction values back, albeit not via GPU but that's a separate issue due to my old GPU.
