### ISSUE TITLE
Run Bidmach on very large dataset Spark

### ISSUE THREAD

**Issue by ghost** [BIDData/BIDMach#111]
Hello,

I have a very large dataset on spark clusters.
What is the best way to train the data with Bidmach ?
Suppose we have 5To data, 10To data, 

1) Copy the data on one machine disk and train it ?
2) On the fly copy on disk by batch size of 500Go ?

Thanks

**Comment by jcanny** [comment]
We have some code to do this for KMeans now in BIDMach_Spark. Its still alpha code unfortunately but we're working hard to get it released, and we'll have more learners soon. When you say the data is "on spark clusters" do you mean in HDFS or in Spark RDDs? We can deal with either, through "IteratrorSource" which is a data source that can be hooked directly to a spark dataset and called using map or mappartitions. 

So far though, we havent been able to get the same throughput with Spark as we can if we read directly from local disk (there's a 3x gap for KMeans), even if we use our own SerDe to go in and out of HDFS. 

So the fastest method right now is to write lz4-compressed BIDMach files directly to local disk (dsitributed across as many machines as you have) and read them straight into BIDMach
