### ISSUE TITLE
Can't updating on sparse matrix elements

### ISSUE THREAD

**Issue by serioussam1988** [BIDData/BIDMach#112]
Hi, I am using BIDMach for a week, it is incredibly fast , I really like that
but i face a problem while i want to create and edit a sparse matrix .
I cant update sparse matrix  elements in BIDMach 

I tried simple assignment of   [Accessing_Sparse_Matrix_Elements ](https://github.com/BIDData/BIDMat/wiki/Sparse-matrices#Accessing_Sparse_Matrix_Elements)  in BIDMach Wiki
this is my code

> val ii = icol(1,0,2,1,2,3);
val jj = icol(0,1,1,2,2,2);
val vv = col(0.78, 0.88, 0.13, 0.39, 0.08, 0.64);
val a = sparse(ii,jj,vv)
full(a)
a(0,1)
a(0,1)=0.2

and i get this error :

>scala>  a(0,1)=0.2
java.lang.RuntimeException: operator update not implemented for SMat
  at BIDMat.Mat.notImplemented0(Mat.scala:21)
  at BIDMat.Mat.update(Mat.scala:187)
  ... 33 elided

i am using BIDMach Full bundles which include the CUDA 7.0 runtime.( BIDMach 1.0.3 for 64-bit Linux) on ubuntu 14.04
my scala version is
`scala> util.Properties.versionString
res2: String = version 2.11.2
`

by the way I realized elements are Float when running this command

> scala>a(0,1)
res3: Float = 0.88

but in the tutorial they are Double like this

> scala> a(0,1)
res1: Double = 0.88

**Comment by jcanny** [comment]
Its a conscious choice. SMat's and SDMat's are designed to be "immutable" and to use an compute-efficient internal representation (CSC). Its not impossible to add a mutable sparse matrix type, but we'd have to convert back to CSC format for efficiency, and we'd have to figure out when to do it. We'd also have to support this across sparse matrix types (there are four now). In our own scripts, we typically build matrices first using row, col, val arrays like you did, and then call sparse. 

To be able to dynamically edit SMat's we'd need to add constant-time edit operations - presumably implement them internally as a hash table of triples, and then convert to CSC when its time to do a compute kernel. Do you want to give it a try :).

I'm not sure what was in the tutorial but we now have both single (SMat) and double (SDMat) sparse matrices, so it depends how they were created.

**Comment by serioussam1988** [comment]
thanks,
when i change the a from SMat to SDMat like this:
` a.toSDMat `
it worked.
