### ISSUE TITLE
Saving model matrices

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#115]
BIDMach version: b4b21ec955851375f94d68ef5e33b3ba74bf5059
BIDMat version: e69e2abbf8a59d30728a46b2062045c158a3ef2e
OS: Linux

(Note that the above versions of BIDMach/BIDMat are from March 15, so I'm using the older Net API since the newer one had [this issue I pointed out](https://github.com/BIDData/BIDMach/issues/110), though I'll update soon.)

I am running `Net.scala` and am trying to save my model matrices, which are the weight matrices of the neural network. In my script to run the Net, I have something like the following, with some of the text missing for brevity:

```
// Input the training data and training targets
val (nn0, opts0) = Net.learner( ... ); 

// establish several opts0 options here

// Now create the Net. Note that this uses the OLD API we had.
val net = Net.dnodes3(12, 600, 0.6f, 1, opts0, 2);
opts0.nodeset = net;
val model0 = nn0.model.asInstanceOf[Net];
nn0.train

// Then it trains. Then we can establish the predictions:
val (mm0, mopts0) = Net.predictor(model0, ta);

// And do more analysis here...
```

There are four model matrices, which makes sense because I used three hidden layers. I can access them as I do in the following code.

However, **I would like to save these matrices for later** so that I can load them in at a later date and retain the same neural network model. I noticed that `Model.scala` has a script that saves the model matrices, which seems to be what I need. However, I can't seem to get the method to work due to some null pointer exceptions. The Net code also has an intriguing `saveMetaData` script, but that doesn't save the model matrices; it just creates a JSON file.

```
scala> nn0.modelmats(0)
res19: BIDMat.Mat =
   -0.045297  -0.0092075     0.31523   -0.028672   -0.018180     0.22539     0.30375    -0.14349     0.29993     0.24410     0.40790    0.084087  2.9744e-05    -0.21426    0.051473    -0.21216...
     0.42199    -0.17051    -0.14078     0.58514     0.21920   -0.017404     0.14943   -0.010119   -0.027717   -0.014781    0.091575     0.50787     0.31397     0.12593   -0.068055     0.18638...
    0.041949    0.049116   -0.055485      1.9294     0.26858     0.48547     -2.0694     0.29517    -0.24338    -0.29202     0.33721    -0.17602     0.48330     0.36717    -0.23380    -0.21015...
          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..          ..         ...
scala> nn0.modelmats(3)
res22: BIDMat.Mat = 0.12525,0.067624,0.35373,-0.45435,-0.25183,0.47297,-0.41093,0.027092,-0.40172,0.46529,0.23253,-0.42146,-0.23325,-0.18278,-0.031435,0.32417,0.30976,0.34873,0.33608,0.26926,0.057421,0.44147,0.015059,0.17950,0.28458,0.45523,0.11883,-0.071064,-0.098416,-0.34955,-0.23560,-0.29686,0.18701,0.14608,0.14355,-0.16220,-0.0030155,-0.12076,-0.16777,-0.23969,-0.25831,0.12304,0.44126,-0.11717,0.13880,0.15952,0.054054,0.35824,0.33546,0.43250,-0.29599,0.10132,0.65207,0.061772,0.19662,-0.17348,-0.35279,-0.11931,0.11853,-0.46544,-0.45618,-0.21153,0.43132,-0.50410,0.37630,-0.14499,0.037332,0.23761,-0.080131,0.087651,0.00063339,-0.16071,-0.36716,-0.12308,-0.064445,0.074264,-0.39024,0.10091,0.043229,0.033337,0.42847,-0.38802,0.26867,-0.30104,-0.0010750,-0.18589,-0.41896,-0.14014,0.46983,-...
scala> nn0.modelmats(4)
java.lang.ArrayIndexOutOfBoundsException: 4
  ... 33 elided

scala> nn0.save("nn_models_")
<console>:31: error: value save is not a member of BIDMach.Learner
              nn0.save("nn_models_")
                  ^

scala> nn0.model.save("nn_models_")
java.lang.NullPointerException
  at BIDMach.models.Model$$anonfun$save$1.apply$mcVI$sp(Model.scala:111)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.models.Model.save(Model.scala:108)
  ... 33 elided

scala> model0.save("nn_models_")
java.lang.NullPointerException
  at BIDMach.models.Model$$anonfun$save$1.apply$mcVI$sp(Model.scala:111)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.models.Model.save(Model.scala:108)
  ... 33 elided

scala> model0.saveMetaData("nn_models_")
```

**Comment by jcanny** [comment]
Daniel, If you look at the source code near the exception you'll see:

    for (i <- 0 until modelmats.length) {
      val mat = modelmats(i);
      val f = new File(fname+"modelmat%02d.lz4" format i);
111      f.getParentFile().mkdirs();
      saveMat(fname+"modelmat%02d.lz4" format i, cpu(mat));
    }

The use of "getParentFile" tells you that this pathname should contain a parent directory. If not it returns null. The save function expects a directory name ending with a "/" and saves the model into that directory as separate files. I added some comments to that effect in the source code.
