### ISSUE TITLE
Getting data should "remember" how far it has proceeded

### ISSUE THREAD

**Issue by javadba** [BIDData/BIDMach#122]
I have attempted a few times to get all data using  `scripts\getdata.sh` .  It has never been successful. The script takes at least two hours - I do not actually know how long since (a) can not watch t that long and (b) it has never completed.

The last time I ran it failed this way:

```
Converting movies

Switched on result printing.
Loading MNIST8M data

bunzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bunzip2: Undefined error: 0
	Input file = mnist8m.bz2, output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

```

After having let it run for at least two hours it is problematic to just re-run getdata.sh .  Can it be set up to write a progress/log file - and be able to resume from that point?  

I guess for now a workaround could be if I go inside and doctor up the script to manually skip until mnist8m?

**Comment by jcanny** [comment]
We havent run into this. It sounds like you have a limited internet connection. Yes you can comment out the getmnist line from getdata. 

You could try adding the -C option to the curl command in getmnist8m. Its supposed to resume from a broken download.

**Comment by javadba** [comment]
Doubt the internet speed were the issue: I have comcast blast which runs @65Mbps on wireless per speedtest.net. Will keep in mind the -C option next time.
