### ISSUE TITLE
Model training get stuck

### ISSUE THREAD

**Issue by manvendratomar** [BIDData/BIDMach#131]
I was trying to run BIDMach for Java but it got sucked at training part.
If anyone can help, that would be very helpful

**Comment by jcanny** [comment]
Please post a message explaining what happened so we can fix it. Include:
* your system configuration, memory, GPU if any
* output you saw. 
* steps for us to reproduce the problem, dataset, options etc.

**Comment by manvendratomar** [comment]
It was occurring when you enable parameter putback for mat source file for LDA.
