### ISSUE TITLE
<console>:7: error: not found: value BIDMat

### ISSUE THREAD

**Issue by xinleipan** [BIDData/BIDMach#137]
I encountered this problem after downloading BIDMach and run "./getdevlibs.sh" under root folder. @byeah Could you help to fix this problem? I think it might be the problem of file "BIDMach.jar" but I'm not sure how to fix that. Thanks.

**Comment by xinleipan** [comment]
Sorry to bother. I just solved this by running "mvn package" under BIDMach root folder. Just follow everything under wiki installation part, should be fine.

**Comment by DanielTakeshi** [comment]
Looks like this was resolved. Closing now.

**Comment by svanschalkwyk** [comment]
Would you remove the "./getdevlibs.sh"  file, as it is deprecated please?
Caught me unawares as I had installed BidMach a couple of times before :)

**Comment by DanielTakeshi** [comment]
@svanschalkwyk I think @jcanny might be upgrading or planning on using it later so I don't want to delete things without his permission.
