### ISSUE TITLE
error: value useGPUcache is not a member of object BIDMat.Mat

### ISSUE THREAD

**Issue by xinleipan** [BIDData/BIDMach#139]
I was trying to run BIDMach on a Linux 14.04 machine with CUDA 8.0 reinstalled. I download BIDMach using "git clone git@github.com:BIDData/BIDMach.git" and then use "mvn package" to install it. However, I got the error as denoted in the title. What's wrong?

**Comment by DanielTakeshi** [comment]
Did you run ./getdevlibs.sh?

**Comment by xinleipan** [comment]
I tried to run "./getdevlibs.sh" but it didn't help.

**Comment by jcanny** [comment]
getdevlibs.sh is obsolete. Please check the setup instructions. 

That flag was added to BIDMat recently. Please update your BIDMat lib before posting an issue. Do mvn install in the BIDMat directory to push the updates.

**Comment by DanielTakeshi** [comment]
This seems to have been resolved, so I'll close the issue.

For the benefit of anyone else who might be reading this now, John is correct, the setup instructions have been updated (see the BIDMach and BIDMat Wikipedia pages on "Installing and Running"). The nice thing now is that with the `mvn install` command, we no longer have to compile BIDMat.jar and then copy it over manually. That library *automatically* updates based on the maven repository. For instance, looking at the library files, I now get:

```
daniel@takeshi:~/BIDMach$ ls -lh lib/
total 135M
-rwxrwxr-x 1 daniel daniel  32K Oct 14 13:42 Apache_Commons_Math_LICENSE.txt
-rwxrwxr-x 1 daniel daniel  32K Oct 14 13:42 Apache_License.txt
-rw-rw-r-- 1 daniel daniel 664K Jan 22 15:07 BIDMach-1.1.1-cuda8.0-cpu-linux-x86_64.jar
-rw-rw-r-- 1 daniel daniel 3.7M Jan 22 15:07 BIDMach-1.1.1-cuda8.0-gpu-linux-x86_64.jar
-rwxrwxr-x 1 daniel daniel  737 Oct 14 13:42 bidmach_init.scala
-rw-rw-r-- 1 daniel daniel  22M Jan 22 15:07 BIDMat-1.1.1-cuda8.0-cpu-linux-x86_64.jar
-rw-rw-r-- 1 daniel daniel  24M Jan 22 15:07 BIDMat-1.1.1-cuda8.0-gpu-linux-x86_64.jar
-rw-rw-r-- 1 daniel daniel 2.2M Jan 22 15:07 BIDMat-1.1.1-cuda8.0.jar
-rw-rw-r-- 1 daniel daniel 1.7M Jan 22 15:07 commons-math3-3.2.jar
-rwxrwxr-x 1 daniel daniel  32K Oct 14 13:42 HDF5_Copyright.html
```

(I'm only printing a subset of them.)

I see my BIDMat libraries for the CPU and GPU versions both updated.
