### ISSUE TITLE
Unable to load CUDA libraries

### ISSUE THREAD

**Issue by mathusuthan** [BIDData/BIDMach#165]
Hi,
I built the latest version from Github on Ubuntu 16.04 ...  I have CUDA 8 installed and have set the required paths.

I get the following message :

import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
import BIDMach.Learner
import BIDMach.models.{Click, FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA, RandomForest, SVD}
import BIDMach.networks.Net
import BIDMach.datasources.{DataSource, MatSource, FileSource, SFileSource}
import BIDMach.datasinks.{DataSink, MatSink}
import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, Grad, IncMult, IncNorm, Telescoping, Updater}
import BIDMach.causal.IPTW
**Couldn't load CUDA runtime**

I did check the nvcc --version command :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

In the BIDMach terminal, I tried checking the java path using "System.getProperty("java.library.path", ....)". I get :

/home/mathusuthan/cudnn51/lib64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

How do I ensure CUDA runtime is loaded ... Did I miss anything ? Please help.

**Comment by jcanny** [comment]
Hi,
There is nothing that looks like the CUDA library path in the java library path. Normally CUDA installs into /usr/local/cuda, and you need /usr/local/cuda/lib64 in your LD_LIBRARY_PATH before you start BIDMach (Or any other application that uses CUDA).

**Comment by mathusuthan** [comment]
Hi,
Thank you very much ... I had only my cuDNN in the LD_LIBRARY_PATH ... added the /usr/local/cuda/lib64 to the LD_LIBRARY_PATH and it works now.
