### ISSUE TITLE
size of grid

### ISSUE THREAD

**Issue by maydaygmail** [BIDData/BIDMach#23]
for compute capacity 3.0 or above,  the maximum of grid dimension are (x,y,z = 2147483647,65535,65535)

the code jni/src/GLM.cu
line 78,79
gridp->y = 1 + (nblocks-1)/65536;
gridp->x = 1 + (nblocks-1)/gridp->y;

if nblocks is very large, then gridp->y would exceed

**Comment by jcanny** [comment]
No,
Since nblocks is an integer, its limited to 32 bits, in fact 31 bits if its positive. It always has an upper-bounding product of x and y such that both are <= 65536 (16 bits).
