### ISSUE TITLE
StackDS stuck

### ISSUE THREAD

**Issue by hcbraun** [BIDData/BIDMach#24]
Hi,
i would like to process some large libSVM files which do not fit into memory. I am trying to use a stacked data source for that. But the program gets stuck on accessing the first chunk of my StackedDS object. Accessing the data sources unstacked seems to work fine 

Here is a script demonstrating the problem. It creates a small libSVM file for input
https://gist.github.com/hcbraun/334d3e9c8da7959d0f37#file-svmstack-scala

This is what i am trying to do:
- reading the libSVM file with loadLibSVM
- writing the training data to SMat file (saveSMat)
- writing the  labels to FMat file (saveFMat)
- building SFilesDS from the training SMat files
- building FilesDS from the label FMat files
- combining both data sources with StackDS
- run a learner with logistic regression 

Any suggestions would be appreciated

Best,
Christian

**Comment by hcbraun** [comment]
The executor in the of a StackDS object needs to have a thread pool size of at least **4**. Works just fine then
Cheers,
Christian

**Comment by jcanny** [comment]
Thanks for figuring that out. I'll add that change. btw, StackedDS sounds like more than you need. You can use FilesDS with multiple input files, and with both sparse and dense data, even in the same source. If you give FilesDS two lists of files, one sparse and one dense, it will return a block of each when you call 'next' on the source. Its likely to be faster (needs fewer threads and has better synchronization) that using a stackedDS on two sources.
