### ISSUE TITLE
IPython notebook in tutorials report that the 'kernel died'

### ISSUE THREAD

**Issue by helgammal** [BIDData/BIDMach#31]
A minor annoyance: when opening the tutorials (via './bidmach notebook') and browsing to the tutorials then clicking any one tutorial, we get this message from IPython. 
![image](https://cloud.githubusercontent.com/assets/7671960/6377520/74609686-bcd9-11e4-8d64-97009ff40c01.png)

Followed by this: 
![image](https://cloud.githubusercontent.com/assets/7671960/6377526/8ba572c6-bcd9-11e4-8237-e677169cbcac.png)

I looked at this and it might be a false alarm from IPython and there is a suggested solution [here] (https://github.com/ipython/ipython/issues/1198/).

**Comment by jcanny** [comment]
No, this was a genuine problem, but it was fixed. Grab the latest bundle or pull from github. It was a script problem so you dont need to recompile anything.
