### ISSUE TITLE
Instructions for setting up clone of BIDMach repo

### ISSUE THREAD

**Issue by davclark** [BIDData/BIDMach#32]
Should be able to just copy the lib directory from the tarball, but this needs to be documented?

**Comment by davclark** [comment]
We tried copying the lib directory contents from the tarball to a fresh clone, but it seems that the ./bidmach script expects a jar for BIDMach, per the following error:

```
dav@mercury:~/Projects/BIDMach⟫ ./bidmach
Loading /home/dav/Projects/BIDMach/lib/bidmach_init.scala...
import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
<console>:20: error: not found: value BIDMach
       import BIDMach.Learner
              ^
```
(followed by other missing BIDMach libraries).

It seems that ./bidmach_full may be set up to run scala, but I'm not sure what the appropriate way to install scala here is. sbt also appears to download and install scala when I execute `run`, but it doesn't become available for the ./bidmach_full script.

One approach that might help us if you don't have time to figure all of this out is to point us to the packaging script you're using.

cc @helgammal

**Comment by jcanny** [comment]
You need the contents of lib/* but also the main jar: for BIDMach, its BIDMach.jar which is in the root directory. 

All the distributions include scala. The full distributions include the CUDA runtime for people that didnt install the CUDA toolkit on Linux.

**Comment by davclark** [comment]
Will scala still pick up changes to the code if the BIDMach.jar file is there?
