### ISSUE TITLE
Numeric mis-match between token dictionary and parsed file

### ISSUE THREAD

**Issue by davclark** [BIDData/BIDMach#38]
xmltweet indexes tokens from 1, and also stores these tokens in a dictionary file. However, when scala reads in the dictionary, it indexes from 0. So, if you look up the index of a token in the dictionary, it will be one less than the value used in the parsed imat file.

This is easy enough to address by adding or subtracting 1, but we'd like to do this in a way that minimizes error. We talked about perhaps inserting a junk entry as the 0th element when you read the dictionary into Scala. But, we wanted to check with you to see if you had a different idea.

**Comment by jcanny** [comment]
I think the best thing will be to make the indices 0-based (they are 1-based for compatibility with Matlab, which doesnt matter much anymore. 

But to keep things clean I'll leave this to the next release.
