### ISSUE TITLE
Getting started Question

### ISSUE THREAD

**Issue by allykgray** [BIDData/BIDMach#39]
I am just getting started. When I try to run BIDMach root/bidmach I get this error.
Error: Could not find or load main class scala.tools.nsc.MainGenericRunner

I have scala 2.10.5 installed and am on Ubuntu 14.04. Is there a flag I need to add to fix this error?

**Comment by jcanny** [comment]
THere were some script path problems with the initial release that have been fixed. Can you redownload it or update from git?
