### ISSUE TITLE
BIDMach_intro tutorial issue

### ISSUE THREAD

**Issue by mettinger** [BIDData/BIDMach#40]
When I run the first cell of BIDMach_intro I get the following result even though I have CUDA 6.5 installed:

Cant find native CPU libraries
Cant find native HDF5 library
Couldnt load CUDA runtime

Am I missing environment variables?

**Comment by jcanny** [comment]
There's a path problem, but bidmach doesnt use environment variables. We need to know more about how you installed, what kind of machine you're running on, etc.

**Comment by mettinger** [comment]
I'm on OSX (10.9.5) and I simply unzipped to the folder BIDMach_1.0.0-osx-x86_64 on my desktop.  My CUDA base directory is /Developer/NVIDIA/CUDA-6.5

Please let me know anything else you'd like to know about my environment.  Thanks!

**Comment by jcanny** [comment]
I'm assuming you just downloaded it?

If so it may be a path problem. Check whether the path to the desktop 
contains spaces.

After that try "System.getProperty("java.library.path") to see what the 
native path is within Scala.

-John

**Comment by mettinger** [comment]
Hi John,

Yes, I just downloaded it and unzipped.  I'm new to Scala and, to be honest, not an expert in Java so my setup may be incomplete.  

System.getProperty("java.library.path") yields: :/usr/lib64:/lib64:lib:/usr/lib

Could you tell me which files need to be on which paths?  I can find the files on my machine and set the paths in the notebook tutorial using:

System.setProperty("java.library.path", ....)

thanks,
Mark

**Comment by jcanny** [comment]
I'd recommend trying the latest release (1.0.2) again. Try running bidmach directly from a terminal before going into the notebook.

**Comment by mettinger** [comment]
It works!  Thanks!
