### ISSUE TITLE
autoReset default values

### ISSUE THREAD

**Issue by anasrferreira** [BIDData/BIDMach#45]
This is not really an issue, but more of an unintuitive behavior.

When creating a (GLM) learner and predictor in the same function, we get by default: options.autoReset = false (for both learner opts and predictor opts).
On the other hand, when creating a GLM learner and GLM predictor independently, we get by default options.autoReset = true for both of them. This means that GLM predictor will reset the model weights (modelmat) to zero after running "predict" once. Should a predictor be able to reset the model weights resulting from a learner?

**Comment by jcanny** [comment]
This has been changed so autoreset is left alone. It was a workaround behavior that isnt needed anymore.
