### ISSUE TITLE
parallel graph processing with BIDmach?

### ISSUE THREAD

**Issue by Navgeet** [BIDData/BIDMach#46]
Hi. Is it possible to do parallel graph processing using BIDMach? Specifically I'm looking to implement belief propagation on factor graphs.

**Comment by jcanny** [comment]
You might want to take a look at the BayesNet Learner that we've been working on recently. Its doing inference on discrete graphical models, but is quite easily extensible to factor graphs. In fact we do normalization on the fly which means its already set up for arbitrary (un-normalized) factors.

**Comment by jcanny** [comment]
PS, BayesNet is designed to use both parallelism over the graph and over instances (observations on the graph). This keeps the GPU pretty busy and gives us very high throughput.
