### ISSUE TITLE
DNN learnerX doesn't respect addConstFeat option

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMach#50]
It seems like building a dnn learner using the learnerX method with `addConstFeat=true` doesn't actually add a constant feature. 

```
val (nn,opts)= DNN.learnerX(indir+"trainData%03d.smat.lz4",indir+"trainLabels%03d.fmat.lz4");

opts.aopts = opts; 

opts.featType = 1;              
opts.addConstFeat = true;       

opts.batchSize=5000;
opts.reg1weight = 0.0001;
opts.lrate = 0.5f;
opts.texp = 0.4f;
opts.npasses = 1;

opts.links = iones(nrValidMoods,1);

DNN.dlayers(5,200,0.5f,132,opts,2);
```
After training using `nn.train`, I run
```
size(nn.modelmats(0))
res17: (Int, Int) = (200,75000)
```
The input data has 75000 features, so with the const feature this should be (200,75001). Note that predict behaves as expected and adds the const feature, so with this option `nn.predict` gives a dimension mismatch error.

**Comment by jcanny** [comment]
Your correct, but please dont use the DNN class anymore. Its been replaced by the Net class. 

re: constant features (or bias vectors in DNNs), there are two flags related to this. addConstFeat operates on the input datasource and adds a row of ones. 

useBias s a flag which applies to all the Layer instances in a network and causes them to use a bias vector by adding a row of ones to their data matrix. Its global by default but you can set it for each layer if you want to.
