### ISSUE TITLE
AWS image for 1.0.3 and loading trained models

### ISSUE THREAD

**Issue by rkommineni77** [BIDData/BIDMach#53]
Is there a plan for publishing AWS image for 1.0.3? We have tried creating one but ran into much of problems.  
One of the main thing I was looking for using predictor for KMeans. predictor method is missing in 1.0.So, I can use 1.0 to train the models and use 1.0.3 for prediction.  Is there a way to save the model created using 1.0 and use it for prediction in 1.0.3? I was able to save the model in 1.0. I couldn't find any example of how to load an existing model (for KMeans).

Regards

**Comment by rkommineni77** [comment]
Here is what I am doing loading an existing model. After training is done, save the model:
saveFMat("mydata/learnedModel0.txt",  FMat(nn.modelmats(0)))
saveFMat("mydata/learnedModel1.txt",  FMat(nn.modelmats(1)))

Load the models through: 
val model = nn.model.asInstanceOf[KMeans]
val modelData1 = loadFMat("mydata/learnedModel0.txt")
val modelData2 = loadFMat("mydata/learnedModel1.txt")
model.setmodelmats(Array(modelData1,modelData2))

and then do prediction. Does this look about right? is there any other  efficient way of doing this?

**Comment by jcanny** [comment]
That's exactly right. 
I just add some save and load methods to the "Model" class to automate some of this. You can also use those. Note that if you dont need the models to be human-readable, saving/loading with LZ4 compression is much faster than text.
