### ISSUE TITLE
Kmeans with Large DataSet

### ISSUE THREAD

**Issue by gustavolacerdas** [BIDData/BIDMach#62]
I run to this code:
val c = rand(15,123254688)
val (nn, opts) = KMeans.learner(c)
nn.train

The code runs perfectly, but when i run this:

nn.modelmat

My output is that:

res3: BIDMat.Mat =
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..

I want to know why this output is a not a number, and how can i see the result of kmeans.

**Comment by jcanny** [comment]
I couldnt reproduce the problem, and got float centroid values out. There might be a problem with your setup. Are you able to run the workout.ssc script after loading the datasets?
