### ISSUE TITLE
Wiki tutorials NBViewer links broken

### ISSUE THREAD

**Issue by danielunderwood** [BIDData/BIDMach#68]
The NBViewer links on [this wiki page](https://github.com/BIDData/BIDMach/wiki/BIDMach-Tutorials) are broken. Going to the NBViewer homepage and pasting in the links to the notebooks in the repo seems to work fine, so I'm not sure if it is a change with this repo or with NBViewer.

**Comment by kjameslubin** [comment]
The tutorials that ship with the install work do though.

**Comment by jcanny** [comment]
Just fixed the wiki page links to match the current tutorials.
