### ISSUE TITLE
Notebook server is not visible from outside Amazon EC2 machine

### ISSUE THREAD

**Issue by o-mdr** [BIDData/BIDMach#71]
I've started EC2 machine with BIDMach preinstalled on it, as described in http://bid2.berkeley.edu/bid-data-project/download/

After starting the machine and opening up firewall for the notebook server, I started the server with

    bidmach notebook

But the server didn't bind to all the network interfaces and was only visible from its own IP address.

**Comment by jcanny** [comment]
This is almost surely an Ipython issue. Did you try opening a regular ipython notebook? 
To use an ipython notebook remotely you need to either:
* Use an X11 server on your local machine and enable X tunneling with ssh -X or ssh -Y
* Create tunnels for the typical ipython ports on 8888 etc. with ssh -L 8888:localhost:8888 and then connect to localhost:8888 from your local browser
