### ISSUE TITLE
Use rsync (or git, or similar) for download scripts

### ISSUE THREAD

**Issue by kjameslubin** [BIDData/BIDMach#73]
The scripts in BIDMach often download a bunch of data.. Since the libraries get updated from time to time, one has to rerun ./getdevlibs.sh. rsync would speed this up. I may be able to make this change without issue but I'm not sure if rsync need more information than it has (e.g. you need a login on the remote). There could be licensing issues which might prevent library hosting on git

**Comment by jcanny** [comment]
rsync is a more complex protocol than you need. For clients with wget, the -N option should do this. I'll add that change. For clients with curl only, I'm not sure if there is an option.
