### ISSUE TITLE
BIDMat/BIDMach can not load native CPU Libraries

### ISSUE THREAD

**Issue by husnusensoy** [BIDData/BIDMach#75]
$  ~/Downloads/BIDMach_1.0.3-osx-x86_64  ./bidmach
Loading /Users/husnusensoy/Downloads/BIDMach_1.0.3-osx-x86_64/lib/bidmach_init.scala...
import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
import BIDMach.Learner
import BIDMach.models.{FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA, RandomForest}
import BIDMach.networks.DNN
import BIDMach.datasources.{DataSource, MatDS, FilesDS, SFilesDS}
import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, IncMult, IncNorm, Telescoping}
import BIDMach.causal.IPTW
**Cant find native CPU libraries**
Cant find native HDF5 library
Couldnt load CUDA runtime

Welcome to Scala version 2.11.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala> Mat.checkMKL
Cant find native HDF5 library

Also it seems that checkMKL only checks for HDF5 ?!?

**Comment by jcanny** [comment]
The 1.03 release has issues these kinds of issues when run on a machine that doesnt have CUDA installed (long story). This was fixed some time ago in the main branch. You can always get the latest version by cloning BIDMach from github:
git clone http://github.com/BIDData/BIDMach.git 
and then in the main BIDMach directory do:
./getdevlibs.sh
to pull the compiled libraries for your platform from the project web site.

**Comment by svanschalkwyk** [comment]
Getting it on latest build and ./getdevlibs.sh is deprecated. 
Scala> import BIDMat.{CMat,CSMat,DMat,Dict,IDict,FMat,GMat,GIMat,GSMat,GSDMat,HMat,IMat,Image,LMat,Mat,SMat,SBMat,SDMat}
import BIDMat.{CMat, CSMat, DMat, Dict, IDict, FMat, GMat, GIMat, GSMat, GSDMat, HMat, IMat, Image, LMat, Mat, SMat, SBMat, SDMat}
scala> Mat.checkMKL
Cant find native HDF5 library
