### ISSUE TITLE
JPlotting is not a member of package BIDMat

### ISSUE THREAD

**Issue by shethsh** [BIDData/BIDMach#78]
Installed BIDMach on Ubuntu machine(EC2 g2.8x large) and getting errors about a few things missing 
1) JPlotting is not a member of package BIDMat
2) error: object MatSource is not a member of package BIDMach.datasources
              import BIDMach.datasources.{MatSource,FileSource,SFileSource}
3) FileSource
4) SFileSource
5) <console>:41: error: value setInline is not a member of object BIDMat.Mat
              Mat.setInline

**Comment by jcanny** [comment]
Looks like you've got a stale BIDMat and BIDMach jar. I'm not sure how you installed, but the easiest way is to clone the github repo and then type 
./getdevlibs.sh
from the main BIDMach directory. 

If you pull from the repo later on, its a good idea to run getdevlibs.sh again to get any new libs. We'll have a maven version up soon, but for now this solution should work almost as well.

**Comment by shethsh** [comment]
Yes. I realised I had previous version. Pulling from the latest version fixed the issue.
Thanks.
