### ISSUE TITLE
bidmach doesn't start due to JRE lack of memory

### ISSUE THREAD

**Issue by mjparrott** [BIDData/BIDMach#80]
I cloned the most recent version of the master branch of this repository, and ran ./getdevlibs.sh to get everything needed to compile the branch. I was able to run ./sbt package just fine and get bidmach compiled. When trying to run ./bidmach, it says there is insufficient memory for the Java Runtime Environment to continue, and it looks like it is looking for ~10gb of memory. However, downloading one of the Linux bundles from http://bid2.berkeley.edu/bid-data-project/download/ and running ./bidmach works just fine.

**Comment by jcanny** [comment]
How much memory does your machine have? Adjust the first lines in the BIDMach/bidmach script to stay under your machine's limit. Make sure there arent other processes commiting lots of memory

**Comment by mjparrott** [comment]
That was it, thanks!
