### ISSUE TITLE
invalid command in split_ratings.sh in getmovielens.sh script

### ISSUE THREAD

**Issue by christopher5106** [BIDData/BIDMach#88]
Dears,

To get a better compatibility with mac os and avoid an error, let's add `xargs` command in the pipe to trim the whitespaces on mac os :

```
RATINGS_COUNT=`wc -l ratings.dat | xargs | cut -d ' ' -f 1`
```

instead of

```
RATINGS_COUNT=`wc -l ratings.dat  | cut -d ' ' -f 1`
```

that is not working.

Also the line 

```
head -`expr \( $i - 1 \) \* $SET_SIZE` ratings.dat > r$i.train
```

gives

> head: illegal line count -- 0

for $i = 1. Is it normal ?

Thanks!

**Comment by jcanny** [comment]
If you look carefully, you'll notice that script is downloaded from the movielens project. Send them a note here:

http://grouplens.org/datasets/movielens/

**Comment by christopher5106** [comment]
Done

**Comment by maxharp3r** [comment]
Thanks for the feedback. I edited the shell script to work on OSX, essentially as suggested by @christopher5106. The "illegal line count" line is a warning (printed on OSX only) that can be ignored.

**Comment by christopher5106** [comment]
OK, works perfectly
