### ISSUE TITLE
How to get files data sources for Nets?

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#92]
I'm using BIDMach and BIDMat that I updated this morning.

I downloaded the rcv1 data using the script provided in the `scripts` directory. Then I split the training data (the data plus the categories) into five parts, each of equal size. I did this to test the files data source, as you'll see later.

Here is the list of files in my `data/rcv1` directory. Note that the original training files were `docs.smat.lz4` and `cats.fmat.lz4`, where each document is part of multiple categories (here it's 103). 

```
seita@bitter:~/BIDMach$ ls -lh data/rcv1/
total 708M
-rw-rw-r-- 1 seita seita  428 Feb 12 10:09 catname.cnt.imat
-rw-rw-r-- 1 seita seita  10M Feb 12 10:09 catname.imat
-rw-rw-r-- 1 seita seita  817 Feb 12 10:09 catname.sbmat
-rw-rw-r-- 1 seita seita  14M Feb 12 10:11 cats.fmat.lz4
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:17 cats_part00.fmat.lz4
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:17 cats_part01.fmat.lz4
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:17 cats_part02.fmat.lz4
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:18 cats_part03.fmat.lz4
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:18 cats_part04.fmat.lz4
-rw-rw-r-- 1 seita seita  10M Feb 12 10:09 dmy.imat
-rw-rw-r-- 1 seita seita  10M Feb 12 10:09 docid.imat
-rw-rw-r-- 1 seita seita  46M Feb 12 10:14 docs_part00.smat.lz4
-rw-rw-r-- 1 seita seita  46M Feb 12 10:14 docs_part01.smat.lz4
-rw-rw-r-- 1 seita seita  47M Feb 12 10:14 docs_part02.smat.lz4
-rw-rw-r-- 1 seita seita  45M Feb 12 10:14 docs_part03.smat.lz4
-rw-rw-r-- 1 seita seita  47M Feb 12 10:14 docs_part04.smat.lz4
-rw-rw-r-- 1 seita seita 230M Feb 12 10:11 docs.smat.lz4
-rw-rw-r-- 1 seita seita 3.0M Feb 12 10:11 lkup.imat.lz4
-rw-rw-r-- 1 seita seita  43M Apr 10  2004 lyrl2004_tokens_test_pt0.dat.gz
-rw-rw-r-- 1 seita seita  44M Apr  9  2004 lyrl2004_tokens_test_pt1.dat.gz
-rw-rw-r-- 1 seita seita  43M Apr  9  2004 lyrl2004_tokens_test_pt2.dat.gz
-rw-rw-r-- 1 seita seita  41M Apr 10  2004 lyrl2004_tokens_test_pt3.dat.gz
-rw-rw-r-- 1 seita seita 4.9M Apr 11  2004 lyrl2004_tokens_train.dat.gz
-rw-rw-r-- 1 seita seita 7.0M Apr  9  2004 rcv1-v2.topics.qrels.gz
-rw-rw-r-- 1 seita seita 2.7M Feb 12 10:10 sdict.sbmat.lz4
-rw-rw-r-- 1 seita seita  40K Feb 12 10:10 swcount.imat.lz4
-rw-rw-r-- 1 seita seita 394K Feb 12 10:11 testcats.fmat.lz4
-rw-rw-r-- 1 seita seita 6.7M Feb 12 10:11 testdocs.smat.lz4
-rw-rw-r-- 1 seita seita  91K Feb 12 10:11 testlkup.imat.lz4
drwxrwxr-x 2 seita seita 4.0K Feb 12 10:10 tokenized
seita@bitter:~/BIDMach$ 
```

I then used a script based on the example `testnet.ssc` to run the Net learner. Here's a relevant part of the script that one can copy and paste and it should work:

```
import BIDMach.networks.Net

// 'rr' is to help randomize the data via columns
val dir = "data/rcv1/"
val a0 = loadSMat(dir + "docs.smat.lz4")
val c0 = loadFMat(dir + "cats.fmat.lz4")
val rr = rand(c0.ncols,1);
val (ss, ii) = sort2(rr);
val train_docs = a0(?,ii);
val train_cats = c0(?,ii);

val opts = new Net.LearnOptions
opts.aopts = opts
opts.batchSize = 2000
opts.reg1weight = 0.0001
opts.npasses = 1 
opts.addConstFeat = false;
opts.links = iones(103,1);
opts.lrate = 0.4f // best for 6-layer
opts.lrate = 0.2f 
opts.texp = 0.4f
opts.nweight = 1e-4f

// Use d4nodes for having normalization and dropout
val net = Net.dnodes4(7,500,0.5f,103,opts,2);
val (nn,opts0) = Net.learnerX(train_docs, train_cats);
opts0.nodeset = net 
opts0.npasses = 20
val dnn = nn.model.asInstanceOf[Net]
nn.train
```

This will train normally without issues (run `./bidmach scripts/script_name.ssc` with the `script_name.ssc` code as above).

BUT .... when I try using files data sources, as in the following script I get a null pointer exception.

```
import BIDMach.networks.Net

val dir = "data/rcv1/"
val opts = new Net.LearnOptions
opts.aopts = opts
opts.batchSize = 2000
opts.reg1weight = 0.0001
opts.npasses = 1 
opts.addConstFeat = false;
opts.links = iones(103,1);
opts.lrate = 0.4f // best for 6-layer
opts.lrate = 0.2f 
opts.texp = 0.4f
opts.nweight = 1e-4f

val net = Net.dnodes4(7,500,0.5f,103,opts,2);
val (nn,opts0) = Net.learnerX(dir + "docs_part%02d.smat.lz4", dir + "cats_part%02d.fmat.lz4");
opts0.nodeset = net 
opts0.npasses = 20
val dnn = nn.model.asInstanceOf[Net]
nn.train
```

And the output is:

```
import BIDMach.networks.Net
dir: String = data/rcv1/
opts: BIDMach.networks.Net.LearnOptions = BIDMach.networks.Net$LearnOptions@43e9f14d
opts.aopts: BIDMach.updaters.ADAGrad.Opts = BIDMach.networks.Net$LearnOptions@43e9f14d
opts.batchSize: Int = 2000
opts.reg1weight: BIDMat.FMat = 0.00010000
opts.npasses: Int = 1
opts.addConstFeat: Boolean = false
opts.links: BIDMat.IMat =    1
   1
   1
  ..
opts.lrate: BIDMat.FMat = 0.40000
opts.lrate: BIDMat.FMat = 0.20000
opts.texp: BIDMat.FMat = 0.40000
opts.nweight: Float = 1.0E-4
net: BIDMach.networks.layers.NodeSet = BIDMach.networks.layers.NodeSet@6e448
java.lang.NullPointerException
  at BIDMach.networks.Net$.learnerX(Net.scala:416)
  at BIDMach.networks.Net$.learnerX(Net.scala:404)
  ... 54 elided
<console>:34: error: not found: value opts0
val $ires10 = opts0.nodeset
              ^
<console>:31: error: not found: value opts0
       opts0.nodeset = net
       ^
<console>:32: error: not found: value opts0
val $ires11 = opts0.npasses
              ^
<console>:29: error: not found: value opts0
       opts0.npasses = 20
       ^
<console>:29: error: not found: value nn
       val dnn = nn.model.asInstanceOf[Net]
                 ^
<console>:30: error: not found: value nn
              nn.train
              ^

Welcome to Scala version 2.11.2 (OpenJDK 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.
```

As far as I can tell, the syntax "docs_part%02d.smat.lz4" is used to specify files data sources, and I have files numbered 00 through 04. By looking at the error trace, it is calling the learner code that takes in two files data sources together. I'm assuming this is legal; each file source is a matrix where each column represents elements. I did a similar thing for the now deprecated DNN class and it seemed to work there without issues.

Would it be possible to see an example of how to use files data sources, especially for the supervised case where we have data and targets? The BIDMach tutorials use LDA but the syntax is what I did here with the "%02d" formatting option.

**Comment by DanielTakeshi** [comment]
Sorry, I posted this prematurely by clicking "enter" by mistake. The post is properly updated now.

**Comment by jcanny** [comment]
General documentation for Data Sources is here. 
https://github.com/BIDData/BIDMach/wiki

Most learners have convenience functions that take a list of file names with wildcard indices and create FileSources with them. See this learner in GLM: If you place the GLM model with a Net, you should get what you're looking for:

  // A learner that uses a files data source specified by a list of strings.  
  def learner(fnames:List[String]):(Learner, FGOptions) = {
    val mopts = new FGOptions;
    mopts.lrate = 1f;
    val model = new GLM(mopts);
    mopts.fnames = fnames.map((a:String) => FileSource.simpleEnum(a,1,0));
    implicit val ec = threadPool(fnames.length + 2);
    val ds = new FileSource(mopts)(ec);    
    val mm = new Learner(
        ds, 
        model, 
        mkRegularizer(mopts),    // set this to null
        new ADAGrad(mopts), 
        null,
        mopts)
    (mm, mopts)
  }

**Comment by jcanny** [comment]
Looks like the FileSource Learner is already defined in the Net class. So all you should need to do is to modify this line in the testnet.scc script

val (nn,opts0) = Net.learnerX(a,c);
to 
val (nn,opts0) = Net.learnerX("docs_part%02d.smat.lz4",cats_part%02d.fmat.lz4")
or whatever is the path to the data files from the directory where you run the script.

**Comment by DanielTakeshi** [comment]
John, thanks for the feedback.

I think if you got this message by email (and not on github directly) you may have seen my old post which I had posted prematurely by mistake (i.e., I only wrote about 1/4 of it before publishing it by mistake). I believe I did what you just mentioned by substituting the a and c with the file pattern, but I will go back and double check, I suppose, and respond back if it doesn't work.

**Comment by DanielTakeshi** [comment]
Never mind, the solution was really simple, the code creates a "net" that uses `opts.targmap.nrows` whereas in the Files Data source, there appears to be no such thing. I believe things are fine now, though I'll still have to learn about how files data sources are manipulated in BIDMach.

I've commented out that line and pushed the changes to master.

**Comment by jcanny** [comment]
On 2/14/2016 10:42 AM, Daniel Seita wrote:
>
> Never mind, the solution was really simple, the code creates a "net" 
> that uses |opts.targmap.nrows| whereas in the Files Data source, there 
> appears to be no such thing. I believe things are fine now, though 
> I'll still have to learn about how files data sources are manipulated 
> in BIDMach.
>
> I've commented out that line and pushed the changes to master.
>
What line Daniel? Please check with me before modifying Master branch code..

-John

**Comment by DanielTakeshi** [comment]
If you look at the Net code:

https://github.com/BIDData/BIDMach/blob/master/src/main/scala/BIDMach/networks/Net.scala

Currently at line 416 I commented out the following line:

    // val net = dnodes(3, 0, 1f, opts.targmap.nrows, opts)                   // default to a 3-node network
Because the 'net' is not used anywhere else in the method, so it is OK to comment it out.
