### ISSUE TITLE
scala 2.10

### ISSUE THREAD

**Issue by christopher5106** [BIDData/BIDMach#94]
Is it compatible ? I've read it was ok...
For BIDMat it is ok.
For BIDMach, I get this error message : 

```
./sbt package
[info] Set current project to BIDMach (in build file:/home/ec2-user/BIDMach/)
[warn] Credentials file /home/ec2-user/.ivy2/.credentials does not exist
[info] Updating {file:/home/ec2-user/BIDMach/}bidmach...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 83 Scala sources and 9 Java sources to /home/ec2-user/BIDMach/target/scala-2.10/classes...
[error] /home/ec2-user/BIDMach/src/main/scala/BIDMach/networks/DNN.scala:647: type mismatch;
[error]  found   : net.FCLayer
[error]  required: net.Layer
[error]   		fclayer;
[error]   		^
[error] /home/ec2-user/BIDMach/src/main/scala/BIDMach/networks/DNN.scala:652: type mismatch;
[error]  found   : net.ReLULayer
[error]  required: net.Layer
[error]     override def factory(net:DNN) = new net.ReLULayer;
[error]                                     ^

```

**Comment by jcanny** [comment]
Could you please explain what you're trying to do?  If its compile BIDMach under scala 2.10, then taht's untried. 

I dont think it will work, but it also looks like the errors above come from a partial compilation with old object files. Make sure to "./sbt clean" first, and make sure you copy the BIDMat.jar built for 2.10 into the BIDMach/lib directory.

**Comment by christopher5106** [comment]
Spark-EC2 launches Spark with Scala 2.10. Not easy to change the way Spark-ec2 works. I would prefer to compile BIDMach under Scala 2.10
Yes, I did clean before and copied the BIDMat.jar but error remains.

**Comment by christopher5106** [comment]
I compiled Spark for Scala 2.11, this solved my issue
http://christopher5106.github.io/big/data/2016/01/27/two-AMI-to-create-the-fastest-cluster-with-gpu-at-the-minimal-engineering-cost-with-EC2-NVIDIA-Spark-and-BIDMach.html#cluster_of_gpu

**Comment by jcanny** [comment]
Turns out all the compilation problems with Scala 2.10 were in the DNN class, which is deprecated anyway (Replaced by the "Net" class). I removed it from BIDMach 1.1.0 onwards. You should be able to compile under 2.10 now. I added the sbt files for both 2.10 and 2.11 in the main BIDMat and BIDMach directories.
