### ISSUE TITLE
BIDMach FileSource Adding A Line of 0 Between Data

### ISSUE THREAD

**Issue by qiaojianjack** [BIDData/BIDMach#97]
I piped 2 FMat file (each contains a 1000001*7 matrix) into FileSource and set batchSize = 10000 and dorows = true. But in the output batches, FileSource added a row of 0 between the end of 1st file and the start of 2nd file. 

I think the bug might be because that the number of rows in each file is not a multiple of batchSize, but I'm not sure why FileSource would add a line of 0 there. Could anyone take a look to see if there is any subtle bugs, or if this is a intended behavior?

Thanks,
Jack

**Comment by jcanny** [comment]
I'm assuming your file size was 7*1000001. Please try to use file sizes which are multiples of the minibatch size.
